"""create column

Revision ID: 546d86679ec5
Revises: f7424adc6c86
Create Date: 2023-10-24 11:22:18.089990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546d86679ec5'
down_revision = 'f7424adc6c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
